name: oction-create-deployment
description: |
  This action implements `POST` request to `/repos/{owner}/{repo}/deployments`

inputs:
  token:
    description: |
      Token to authenticate the request
    required: true
  owner:
    description: |
      owner parameter
    required: false
  repo:
    description: |
      repo parameter
    required: false
  ref:
    description: |
      The ref to deploy. This can be a branch, tag, or SHA.
    required: true
  task:
    description: |
      Specifies a task to execute (e.g., `deploy` or `deploy:migrations`).
    required: false
  auto_merge:
    description: |
      Attempts to automatically merge the default branch into the requested ref, if it's behind the default branch.
    required: false
  required_contexts:
    description: |
      The [status](https://developer.github.com/v3/repos/statuses/) contexts to verify against commit status checks. If you omit this parameter, GitHub verifies all unique contexts before creating a deployment. To bypass checking entirely, pass `<<EMPTY>>`. To provide a list of contexts, use a comma-separated string (eg. `success,pending`). Defaults to all unique contexts.
    required: false
  payload:
    description: |
      JSON payload with extra information about the deployment.
    required: false
  environment:
    description: |
      Name for the target deployment environment (e.g., `production`, `staging`, `qa`).
    required: false
  description:
    description: |
      Short description of the deployment.
    required: false
  transient_environment:
    description: |
      Specifies if the given environment is specific to the deployment and will no longer exist at some point in the future. Default: `false`   **Note:** This parameter requires you to use the [`application/vnd.github.ant-man-preview+json`](https://developer.github.com/v3/previews/#enhanced-deployments) custom media type. **Note:** This parameter requires you to use the [`application/vnd.github.ant-man-preview+json`](https://developer.github.com/v3/previews/#enhanced-deployments) custom media type.
    required: false
  production_environment:
    description: |
      Specifies if the given environment is one that end-users directly interact with. Default: `true` when `environment` is `production` and `false` otherwise.   **Note:** This parameter requires you to use the [`application/vnd.github.ant-man-preview+json`](https://developer.github.com/v3/previews/#enhanced-deployments) custom media type.
    required: false

runs:
  using: node12
  main: index.js

branding:
  icon: upload-cloud
  color: green
